# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'OrchCon'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'OrchCon'
    testProjectPath: '$(Build.SourcesDirectory)'
    folderName: 'Shared'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'OrchCon'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'